// Renders assets/logo.svg to the PNG sizes listed in the manifest, and generates the stylesheet
// that puts the logo on the Gmail button.
// Usage: CHROME=/path/to/chrome node scripts/build-icons.js
const { chromium } = require('playwright-core');
const fs = require('node:fs');
const path = require('node:path');

const svg = fs.readFileSync(path.join(__dirname, '..', '..', 'assets', 'logo.svg'), 'utf8');
const out = path.join(__dirname, '..', 'icons');

(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROME, args: ['--no-sandbox'] });
  const page = await browser.newPage();
  for (const size of [16, 32, 48, 128]) {
    await page.setViewportSize({ width: size, height: size });
    await page.setContent(`<style>html,body{margin:0;background:transparent}svg{display:block;width:${size}px;height:${size}px}</style>${svg}`);
    await page.screenshot({ path: path.join(out, `icon-${size}.png`), omitBackground: true, clip: { x: 0, y: 0, width: size, height: size } });
  }
  await browser.close();

  // The small logo on the Gmail button is inlined as a data URI, so the page needs no access to extension files.
  const b64 = fs.readFileSync(path.join(out, 'icon-32.png')).toString('base64');
  fs.writeFileSync(path.join(__dirname, '..', 'src', 'logo.css'),
    '/* generated by scripts/build-icons.js */\n' +
    `.plume-btn::before { content: ''; display: inline-block; width: 18px; height: 18px; margin-right: 8px; vertical-align: -4px; background: url(data:image/png;base64,${b64}) center / contain no-repeat; }\n`);
})();
